collection_name: agent
persist_directory: rag/chroma_db
k: 3
data_path: data
md5_hex_store: md5.txt
allowed_knowledge_file_type: ["txt", "pdf"]

#chunk_size: 200
#chunk_overlap: 20
#separators: ["\n\n", "\n", ".", "!", "?", "。", "！", " ", ""]
# 将块大小调大，确保能容纳一整个长对话
chunk_size: 1500
# 对话与对话之间是独立的，不需要重叠
chunk_overlap: 0
# 把自定义的对话分隔符放在第一优先级
separators: ["\n\n---\n\n", "\n\n", "\n", "。"]